<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dokter extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dokter_model');
            $s = $this->session->userdata('status');
        if($s != "adminlogin"){ redirect("login_admin"); }
    } 

    /*
     * Listing of dokter
     */
    function index()
    {
        $data['title'] = 'Data Dokter';
        $data['dokter'] = $this->Dokter_model->tampil()->result();
        
        $this->load->view('admin/layout/nav',$data);
		$this->load->view('admin/dokter/list', $data);
		$this->load->view('admin/layout/footer');  
    }

    /*
     * Adding a new dokter
     */
    function add()
    {   
        $data['title'] = "Tambah Dokter";
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_poli','Nama Poli','required');
		$this->form_validation->set_rules('nama_dokter','Nama Dokter','required');
		$this->form_validation->set_rules('jk_dokter','Jk Dokter','required');
		$this->form_validation->set_rules('ttl_dokter','Ttl Dokter','required');
		$this->form_validation->set_rules('no_telp','No Telp','required|max_length[13]');
		$this->form_validation->set_rules('alamat','Alamat','required');
		$this->form_validation->set_rules('spesialis','Spesialis','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_poli' => $this->input->post('id_poli'),
				'jk_dokter' => $this->input->post('jk_dokter'),
				'nama_dokter' => $this->input->post('nama_dokter'),
				'ttl_dokter' => $this->input->post('ttl_dokter'),
				'no_telp' => $this->input->post('no_telp'),
				'alamat' => $this->input->post('alamat'),
				'spesialis' => $this->input->post('spesialis'),
            );
            
            $dokter_id = $this->Dokter_model->add_dokter($params);
            redirect('dokter/index');
        }
        else
        {
			$this->load->model('Poli_model');
			$data['poli'] = $this->Poli_model->tampil()->result();
            
            $data['_view'] = 'dokter/add';
            $this->load->view('admin/layout/nav',$data);
            $this->load->view('admin/dokter/add', $data);
            $this->load->view('admin/layout/footer'); 
        }
    }  

    /*
     * Editing a dokter
     */
    function edit($id_dokter)
    {   
        // check if the dokter exists before trying to edit it
        $data['title'] = "Update Dokter";
        $data['dokter'] = $this->Dokter_model->get_dokter($id_dokter);
        
        if(isset($data['dokter']['id_dokter']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_poli','Id Poli','required');
			$this->form_validation->set_rules('nama_dokter','Nama Dokter','required');
			$this->form_validation->set_rules('jk_dokter','Jk Dokter','required');
			$this->form_validation->set_rules('ttl_dokter','Ttl Dokter','required');
			$this->form_validation->set_rules('no_telp','No Telp','required|max_length[13]');
			$this->form_validation->set_rules('alamat','Alamat','required');
			$this->form_validation->set_rules('spesialis','Spesialis','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_poli' => $this->input->post('id_poli'),
					'jk_dokter' => $this->input->post('jk_dokter'),
					'nama_dokter' => $this->input->post('nama_dokter'),
					'ttl_dokter' => $this->input->post('ttl_dokter'),
					'no_telp' => $this->input->post('no_telp'),
					'alamat' => $this->input->post('alamat'),
					'spesialis' => $this->input->post('spesialis'),
                );

                $this->Dokter_model->update_dokter($id_dokter,$params);            
                redirect('dokter/index');
            }
            else
            {
				$this->load->model('Poli_model');
				$data['all_poli'] = $this->Poli_model->get_all_poli();

                $data['_view'] = 'dokter/edit';
                $this->load->view('admin/layout/nav',$data);
                $this->load->view('admin/dokter/edit', $data);
                $this->load->view('admin/layout/footer'); 
            }
        }
        else
            show_error('The dokter you are trying to edit does not exist.');
    } 

    /*
     * Deleting dokter
     */
    function remove($id_dokter)
    {
        $dokter = $this->Dokter_model->get_dokter($id_dokter);

        // check if the dokter exists before trying to delete it
        if(isset($dokter['id_dokter']))
        {
            $this->Dokter_model->delete_dokter($id_dokter);
            redirect('dokter/index');
        }
        else
            show_error('The dokter you are trying to delete does not exist.');
    }
    
}