<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jadwal_model');
        $this->load->helper(array('form', 'url'));
    } 


    function add()
    {   
            $this->load->library('form_validation');
            $this->form_validation->set_rules('jam','Jam','required',
            array('required' => 'Jam harus diisi !'));
            $this->form_validation->set_rules('id_dokter','Dokter','required',
            array('required' => 'Dokter harus diisi !'));
            $this->form_validation->set_rules('hari','Hari','required',
            array('required' => 'Hari harus diisi !'));
            
            if($this->form_validation->run())     
            {   
                $params = array(
                    'id_dokter' => $this->input->post('id_dokter'),
                    'hari' => $this->input->post('hari'),
                    'jam' => $this->input->post('jam'),
                );
                
                $id_jadwal = $this->Jadwal_model->add_jadwal($params);
                redirect('jadwal/tampil');
            }
            else
            {            
                $data['title'] = 'Tambah Jadwal';
                $this->load->model('Dokter_model');
			    $data['dokter'] = $this->Dokter_model->tampil()->result();
                $data['_view'] = 'jadwal/add';
                $this->load->view('admin/layout/nav',$data);
                $this->load->view('admin/jadwal/add', $data);
                $this->load->view('admin/layout/footer');
            }
    }  

    function index()
    {
        $data['jadwal'] = $this->Jadwal_model->tampil()->result();      
        if ($this->input->post('keyword')) {
            $data['jadwal'] = $this->Jadwal_model->searchJadwal();
        }
        $data['title'] = 'Jadwal';

        if($this->session->userdata('status')== 'pasienlogin'){
            $this->load->view('user/user/jadwal',$data);
        } else {
            $this->load->view('user/jadwal', $data);
        }
        
    }
    
    function tampil()
    {
        $data['title'] = 'Jadwal';
        $data['jadwal'] = $this->Jadwal_model->tampil()->result();      

        $this->load->view('admin/layout/nav',$data);
        $this->load->view('admin/jadwal/list',$data);
        $this->load->view('admin/layout/footer'); 
    }

}