<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kontak extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kontak_model');
        $this->load->helper(array('form', 'url'));
    } 

    function add()
    {   
            $nama_pengirim   = $this->input->post('nama_pengirim');
            $email_pengirim = $this->input->post('email_pengirim');
            $messsage      = $this->input->post('message');

            $params = array(
				'nama_pengirim'     => $nama_pengirim,
				'email_pengirim'   => $email_pengirim,
                'message'        => $messsage,
            );
            
            $id_kontak = $this->Kontak_model->add_kontak($params);
            $this->load->view('user/layout/about');
            if($this->session->userdata('status') == 'pasienlogin'){
              redirect('hal_user');  
            }else{
                redirect('umum');
            }
            
    }  

    function index()
    {
        $data['title'] = 'Pesan';
        $data['kontak'] = $this->Kontak_model->tampil()->result();      

        $this->load->view('admin/layout/nav',$data);
        $this->load->view('admin/kontak/list', $data);
        $this->load->view('admin/layout/footer');   
    }
}