<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pemesanan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pemesanan_model');
            $s = $this->session->userdata('status');
        if($s != "adminlogin"){ redirect("login_admin"); }

}   
    /*
     * Listing of pemesanan
     */
    function index()
    {
        $this->load->model('login_model');
        $data['login'] = $this->login_model->tampil()->result();
        $data['title'] = 'Data Pemesanan';
        $this->load->model('Pemesanan_model');    
        $data['pemesanan'] = $this->Pemesanan_model->tampil_admin()->result();
        


        $this->load->view('admin/layout/nav',$data);
        $this->load->view('admin/pemesanan/list', $data);
        $this->load->view('admin/layout/footer'); 
    }
    /*
     * Editing a pemesanan
     */

    function edit($id_pemesanan)
    {   
        // check if the pemesanan exists before trying to edit it
        $data['pemesanan'] = $this->Pemesanan_model->get_pemesanan($id_pemesanan);
        
        if(isset($data['pemesanan']['id_pemesanan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_pasien' => $this->input->post('id_pasien'),
					'id_dokter' => $this->input->post('id_dokter'),
					'id_poli' => $this->input->post('id_poli'),
					'id_waktu' => $this->input->post('id_waktu'),
					'tanggal' => $this->input->post('tanggal'),
                );

                $this->Pemesanan_model->update_pemesanan($id_pemesanan,$params);            
                redirect('pemesanan/index');
            }
            else
            {
                $data['_view'] = 'pemesanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pemesanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting pemesanan
     */
    function remove($id_pemesanan)
    {
        $pemesanan = $this->Pemesanan_model->get_pemesanan($id_pemesanan);

        // check if the pemesanan exists before trying to delete it
        if(isset($pemesanan['id_pemesanan']))
        {
            $this->Pemesanan_model->delete_pemesanan($id_pemesanan);
            redirect('pemesanan/index');
        }
        else
            show_error('The pemesanan you are trying to delete does not exist.');
    }
    
}