
<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
class History_model extends CI_Model
{

function simpan($data){
    
    $query = $this->db->insert('history',$data);
    return $query;
    } 

    function tampil_reservasi(){
        $tabel = 'history';
        return $this->db->get($tabel)->result_array();
    }
}