<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kontak_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

    function add_kontak($params)
    {
        $this->db->insert('kontak',$params);
        return $this->db->insert_id();
    }

    public function tampil()
    {
        $query = $this->db->get('kontak');

        return $query;
    }
    
}
