<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Poli_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
        $this->load->database();
    }

    public function tampil()
    {
        $query = $this->db->get('poli');

        return $query;
    }
    function get_poli($id_poli)
    {
        return $this->db->get_where('poli',array('id_poli'=>$id_poli))->row_array();
    }
    
    /*
     * Get all poli count
     */
    function get_all_poli_count()
    {
        $this->db->from('poli');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all poli
     */
    function get_all_poli($params = array())
    {
        $this->db->order_by('id_poli', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('poli')->result_array();
    }
        
    /*
     * function to add new poli
     */
    function add_poli($params)
    {
        $this->db->insert('poli',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update poli
     */
    function update_poli($params)
    {
        $this->db->where('id_poli',$id_poli);
        return $this->db->update('poli',$params);
    }
    
    /*
     * function to delete poli
     */
    function delete_poli($id_poli)
    {
        return $this->db->delete('poli',array('id_poli'=>$id_poli));
    }
}
